### ISSUE TITLE
Add support for KAFKA as datasource type

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-java#14]
When creating a datasource, let's add `KAFKA` as a supported datasource type.

**Comment by ryanpeterson** [comment]
@wslulciuc did we want to change this to STREAM datasource type?

**Comment by wslulciuc** [comment]
Great question. We'll still want to specify a concrete datasource type. That is, when creating a `KAFKA` datasource it will allow us to correctly associate streams to that source. Using `STREAM` as the datasource is a bit too generic.

In the future, I can imagine a `GCP_PUBSUB` datasource so we'll want to be able to distinguish between streams that are associated with `KAFKA`, `GCP_PUBSUB`, etc

**Comment by wslulciuc** [comment]
Fixed: #20
