### ISSUE TITLE
replace findbugs with spotbugs plugin when moving to gradle 6.0

### ISSUE THREAD

**Issue by soumyasmruti** [MarquezProject/marquez-java#48]
The findbugs plugin has been deprecated. This is scheduled to be removed in Gradle 6.0. Consider using the com.github.spotbugs plugin instead.

**Comment by wslulciuc** [comment]
Thanks for pointing this out, @soumyasmruti! Would you like make the change so `marquez-java` uses [`com.github.spotbugs`](https://plugins.gradle.org/plugin/com.github.spotbugs)?
