### ISSUE TITLE
Add integration test with Marquez API

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-java#52]
Let's define an integration test / sample job that does the following:

1. Run a container using the latest image for Marquez from [Docker Hub](https://hub.docker.com/r/marquezproject/marquez)
2. Use `marquez-java` to write a sample job that will invoke the Marquez backend 
3. Defines a set of checks validating that the client successfully communicated with the Marquez backend

**Comment by wslulciuc** [comment]
@rmuthupandian, assigning this issue to you, Thanks!

**Comment by Meehau** [comment]
@wslulciuc This is linked to https://github.com/MarquezProject/marquez/projects/3#card-42716010 , correct? Was there any progress made? I guess we need this for the release

**Comment by wslulciuc** [comment]
@Meehau I think this is more of a nice to have and rather not block the release. That said, I have a couple approaches in mind (using https://www.testcontainers.org). I'm happy to outline my thoughts here if this would be something you'd like to pick up?

**Comment by Meehau** [comment]
@wslulciuc Sure, please do share. I understand - its nice to have, but still I think will/should be done at some point. In any case, your comments about the suggested approach won't go to waste for sure

**Comment by wslulciuc** [comment]
@Meehau: I will re-open this issue in [`marquez`](https://github.com/MarquezProject/marquez) and outline my thoughts for integration testing there as this repo has been moved to [`marquez/clients/java`](https://github.com/MarquezProject/marquez/tree/main/clients/java). Looking forward to continuing our discussion!
